### ISSUE TITLE
add functional equivalences

### ISSUE THREAD

**Issue by rmsrosa** [sostock/UnitfulEquivalences.jl#4]
I've been working on adding functional equivalences more general than the proportional and anti-proportional equivalences. I've managed to make it work with the same macro, with the arguments arranged as

```julia
@eqrelation name a = f(b)
```

where `a` and `b` are dimensions as in the (anti-)proportional equivalences and `f` is a function with the proper dimensions. The current form for (anti-)proportional equivalences still work fine alongside this.

I am not attempting to do a PR now, but I wanted to show you how this is going so we can discuss whether you think this looks good or not. You can see how I have implemented this in my repo, in the branch

https://github.com/rmsrosa/UnitfulEquivalences.jl/tree/functional-equivalences

although this branch is not up to date with you main branch.

I have added a couple of made-up examples in `runtests.jl`.

It is experimental for now. I should add the Plato-sg conversion in `runtests.jl`. I have figured a way out of the fact that both are non-dimensional, without adding an artificial dimension to them, but at the cost of using separate equivalence names for each direction of the conversion.

I am pretty happy with what I have done, but I wish I knew how to implement directly simpler relations like, say `f(b) = c b^2 + d`, by simply writing
```julia
@eqrelation name a = c * b^2 + c
```
where `b` and `c` are some known constant units, or even just `a = b^2`, but I don't yet know how to have the code figure out from the expression `c * b^2 + d` that `b` is the variable and that the function is `f(b) = c *  b^2 + d`, and so on.

**Comment by sostock** [comment]
I don’t see the point of extending the `@eqrelation` macro like this. The main advantage of the macro is that it defines the methods for conversion in both directions, i.e., you need to write one macro call and get two `edconvert` methods. With the proposed `@eqrelation Name a = f(b)`, one has to use the macro twice to get both directions *and* one has to define the function `f` and its inverse. This is no easier than just writing these functions as `edconvert` methods.

Regarding the Plato–sg conversion, I still don’t think that an equivalence is the correct thing. But I agree that using different dimensions is also ugly. I would prefer a different solution:

The thing about Plato is that it’s not proportional to other units of its dimension. Therefore, it is like an `AffineUnits`, only more complicated. One could define a new type of unit (maybe `QuadraticUnits`) that is related to another unit by a quadratic relation (instead of just an offset, like for `AffineUnits`) and define Plato as such a unit. Then one would just use `uconvert` without `Equivalence`s (since those are for converting between quantities of different dimensions).

**Comment by rmsrosa** [comment]
Fine. I just thought it would be more elegant to have a more consistent way of defining the equivalences, regardless of the form, and it would make it slightly easier for users of the package, which is the aim of any package. Besides, it wouldn't change the current use of the proportional and anti-proportional equivalences. But that's ok, no big deal.

**Comment by sostock** [comment]
Thanks for your input. I’m also in favor of consistency and ease of use, but I don’t think the extended `@eqrelation` macro would achieve that:
* I don’t think it is consistent that some forms of the macro define the conversion in both directions and some only in one direction.
* I don’t think it is easier because one still has to define the function, so one might as well define it as a `edconvert` method. Of course, this has to be properly documented (which I plan to do soon).

**Comment by rmsrosa** [comment]
Well, we could write `@eqrelation y = e * x` and `@eqrelation y = e / x` and have the code figure out whether `rhs.args` has length 3 or 2, to distinguish from `@eqrelation y = f(x)`, and proceed accordingly.

But that is ok. I am just thinking out loud. I understand if using macro just as an alias is considered not good coding. I don't know. I am here to learn. And I am! I have never even browsed over this meta-programming stuff, and it is being fun to learn it, at least. I don't know how else I could help, though.

**Comment by rmsrosa** [comment]
I don't know whether you are considering this or not, but for the moment I am okay with using `edconvert` directly, so I feel I should close the issue since I was the one to raise it.

**Comment by sostock** [comment]
I’m not really considering this, since I think it is not much easier than defining `edconvert` methods.
